/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CastIdRouteImport } from './routes/cast.$id'
import { Route as MovieIdRouteImport } from './routes/movie.$id'
import { Route as TicketMobileappaccess5y2RouteImport } from './routes/ticket.mobileappaccess5y2'
import { Route as WatchIdRouteImport } from './routes/watch.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CastIdRoute = CastIdRouteImport.update({
  id: '/cast/$id',
  path: '/cast/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieIdRoute = MovieIdRouteImport.update({
  id: '/movie/$id',
  path: '/movie/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketMobileappaccess5y2Route =
  TicketMobileappaccess5y2RouteImport.update({
    id: '/ticket/mobileappaccess5y2',
    path: '/ticket/mobileappaccess5y2',
    getParentRoute: () => rootRouteImport,
  } as any)
const WatchIdRoute = WatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/cast/$id': typeof CastIdRoute
  '/movie/$id': typeof MovieIdRoute
  '/ticket/mobileappaccess5y2': typeof TicketMobileappaccess5y2Route
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/cast/$id': typeof CastIdRoute
  '/movie/$id': typeof MovieIdRoute
  '/ticket/mobileappaccess5y2': typeof TicketMobileappaccess5y2Route
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/cast/$id': typeof CastIdRoute
  '/movie/$id': typeof MovieIdRoute
  '/ticket/mobileappaccess5y2': typeof TicketMobileappaccess5y2Route
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/cast/$id'
    | '/movie/$id'
    | '/ticket/mobileappaccess5y2'
    | '/watch/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/cast/$id'
    | '/movie/$id'
    | '/ticket/mobileappaccess5y2'
    | '/watch/$id'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/cast/$id'
    | '/movie/$id'
    | '/ticket/mobileappaccess5y2'
    | '/watch/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  CastIdRoute: typeof CastIdRoute
  MovieIdRoute: typeof MovieIdRoute
  TicketMobileappaccess5y2Route: typeof TicketMobileappaccess5y2Route
  WatchIdRoute: typeof WatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cast/$id': {
      id: '/cast/$id'
      path: '/cast/$id'
      fullPath: '/cast/$id'
      preLoaderRoute: typeof CastIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$id': {
      id: '/movie/$id'
      path: '/movie/$id'
      fullPath: '/movie/$id'
      preLoaderRoute: typeof MovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/mobileappaccess5y2': {
      id: '/ticket/mobileappaccess5y2'
      path: '/ticket/mobileappaccess5y2'
      fullPath: '/ticket/mobileappaccess5y2'
      preLoaderRoute: typeof TicketMobileappaccess5y2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$id': {
      id: '/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof WatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  CastIdRoute: CastIdRoute,
  MovieIdRoute: MovieIdRoute,
  TicketMobileappaccess5y2Route: TicketMobileappaccess5y2Route,
  WatchIdRoute: WatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
